version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    networks:
      - redis-network
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    networks:
      - redis-network
    volumes:
      - redisinsight-data:/data
    ports:
      - "5540:5540"

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local
